added _explain_sorted_merge
geraldywy/CZ4031_proj2 pull request #2
Opened 2023-04-09 15:55 UTC by e-mny

2023-04-09 17:40 UTC, geraldywy requested changes

2023-04-09 17:40 UTC, geraldywy commented on explain.py
>      # print(res[0][0])
Why these changes in return values? These are breaking changes.

2023-04-09 17:40 UTC, geraldywy commented on explain.py
> +
Also, update explainMapping, so sort merge node type is recognised, you must get the exact string value of sort merge node type.

2023-04-10 00:01 UTC, e-mny commented
Have edited changes, please let me know if they're correct

2023-04-10 14:47 UTC, closed without merging